services:
  - type: web
    name: kitoko-hopital
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn conf.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # Vous collerez la valeur de Neon directement dans le Dashboard Render
