# Generated by Django 6.0.3 on 2026-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomService', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFonction', models.CharField(max_length=30)),
            ],
        ),
    ]
