# Generated by Django 6.0.3 on 2026-03-31 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeFonction',
            new_name='Fonction',
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomComplet', models.CharField(max_length=50, null=True)),
                ('sexe', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=50)),
                ('date_register', models.DateField(auto_now_add=True)),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital_site.fonction')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital_site.service')),
            ],
        ),
    ]
