# Generated by Django 6.0.3 on 2026-04-01 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0002_rename_typefonction_fonction_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fonction',
            old_name='typeFonction',
            new_name='fonction',
        ),
        migrations.AddField(
            model_name='profil',
            name='userProfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
