# Generated by Django 6.0.3 on 2026-04-01 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0003_rename_typefonction_fonction_fonction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('sexeP', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Feminin')], max_length=15)),
                ('ageP', models.IntegerField()),
                ('phone_responsable', models.CharField(max_length=15)),
                ('adresseP', models.CharField(max_length=60)),
                ('date_registerP', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital_site.service')),
            ],
        ),
    ]
