# Generated by Django 6.0.3 on 2026-04-02 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_usd_en_cdf', models.DecimalField(decimal_places=2, default=2500.0, max_digits=10)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du Taux',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('valeur_cdf', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('ADM', 'Administratif (Fiche, etc.)'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins / Nursing')], max_length=10)),
                ('prix_cdf', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('prix_fixe_cdf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_fixe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.patient')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_physique', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant_comptable_cdf', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='hopital_site.facture')),
            ],
        ),
    ]
