# Generated by Django 6.0.3 on 2026-04-03 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0005_configurationhopital_depense_prestation_facture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix_fixe_cdf',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_fixe',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='SignesVitaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prelevement', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Ex: 37.5', max_digits=4, verbose_name='Température (°C)')),
                ('tension_arterielle', models.CharField(help_text='Ex: 12/8 ou 120/80', max_length=20, verbose_name='Tension Artérielle')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('frequence_cardiaque', models.IntegerField(verbose_name='Fréquence Cardiaque (BPM)')),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True, verbose_name='Fréquence Respiratoire')),
                ('saturation_oxygene', models.IntegerField(blank=True, help_text='Saturation en oxygène', null=True, verbose_name='Saturation (SpO2 %)')),
                ('infirmier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Infirmier ayant effectué le prélèvement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signes_vitaux', to='hopital_site.patient')),
            ],
            options={
                'verbose_name': 'Signe Vital',
                'verbose_name_plural': 'Signes Vitaux',
                'ordering': ['-date_prelevement'],
            },
        ),
    ]
