# Generated by Django 6.0.3 on 2026-04-03 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0006_alter_facture_prix_fixe_cdf_alter_facture_taux_fixe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(null=True)),
                ('diagnostic', models.TextField()),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.patient')),
                ('signes_vitaux', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='hopital_site.signesvitaux')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenPrescrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField(default=False)),
                ('termine', models.BooleanField(default=False)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_prescrits', to='hopital_site.consultation')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.prestation')),
            ],
        ),
    ]
