# Generated by Django 6.0.3 on 2026-04-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0007_consultation_examenprescrit'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenprescrit',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='examenprescrit',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
