# Generated by Django 6.0.3 on 2026-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0008_examenprescrit_prix_total_examenprescrit_quantite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='date_creation',
            new_name='date_consultation',
        ),
        migrations.RemoveField(
            model_name='examenprescrit',
            name='resultat',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.TextField(default=0, verbose_name='Motif de consultation'),
            preserve_default=False,
        ),
    ]
