# Generated by Django 6.0.3 on 2026-04-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0009_rename_date_creation_consultation_date_consultation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examenprescrit',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenprescrit',
            name='laborantin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_faites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examenprescrit',
            name='resultat_labo',
            field=models.TextField(blank=True, null=True, verbose_name='Résultats / Conclusions'),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='paye',
            field=models.BooleanField(default=False, verbose_name='Est payé (Caisse)'),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='termine',
            field=models.BooleanField(default=False, verbose_name='Analyse terminée (Labo)'),
        ),
    ]
