# Generated by Django 6.0.3 on 2026-04-05 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0010_examenprescrit_date_analyse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='N° de Chambre')),
                ('type_chambre', models.CharField(choices=[('VIP', 'Privée VIP'), ('STANDARD', 'Standard'), ('COMMUNE', 'Salle Commune'), ('REANIMATION', 'Réanimation')], default='STANDARD', max_length=50)),
                ('prix_journalier', models.DecimalField(decimal_places=2, help_text='Prix par jour en CDF', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lit', models.CharField(max_length=10, verbose_name='Nom du Lit')),
                ('est_occupe', models.BooleanField(default=False, verbose_name='Est occupé ?')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hopital_site.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationLit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('est_paye', models.BooleanField(default=False)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.lit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.patient')),
            ],
        ),
    ]
