# Generated by Django 6.0.3 on 2026-04-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0011_chambre_lit_occupationlit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_prescription', models.TextField(verbose_name='Liste des Médicaments')),
                ('instructions_posologie', models.TextField(blank=True, null=True, verbose_name='Posologie et Durée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_delivré', models.BooleanField(default=False, verbose_name='Délivré par la pharmacie')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='hopital_site.consultation')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_prescrites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'ordering': ['-date_creation'],
            },
        ),
    ]
