# Generated by Django 6.0.3 on 2026-04-07 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0012_ordonnance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('quantite_stock_pieces', models.PositiveIntegerField(default=0)),
                ('pieces_par_carton', models.PositiveIntegerField(default=1)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('prix_achat_unitaire_moyen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prix_vente_detail', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente_gros', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='taux_usd_en_cdf',
            field=models.DecimalField(decimal_places=2, default=2250.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LogPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VENTE', 'Vente'), ('ANNULATION', 'Annulation'), ('ENTREE', 'Entrée Stock')], max_length=50)),
                ('details', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(blank=True, max_length=200)),
                ('nb_cartons_recus', models.PositiveIntegerField()),
                ('prix_achat_carton', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='VentePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('total_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validée'), ('ANNULE', 'Annulée')], default='VALIDE', max_length=10)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('type_vente', models.CharField(choices=[('DETAIL', 'Détail'), ('GROS', 'Gros')], max_length=10)),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.medicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='hopital_site.ventepharmacie')),
            ],
        ),
    ]
