# Generated by Django 6.0.3 on 2026-04-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0013_medicament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='forme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
