# Generated by Django 6.0.3 on 2026-04-08 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0014_medicament_dosage_medicament_forme'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='vente_pharmacie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital_site.ventepharmacie'),
        ),
    ]
