# Generated by Django 6.0.3 on 2026-04-09 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0015_facture_vente_pharmacie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventepharmacie',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital_site.patient'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='type_vente',
            field=models.CharField(choices=[('DETAIL', 'Détail'), ('GROS', 'Gros')], default='DETAIL', max_length=10),
        ),
    ]
