# Generated by Django 6.0.3 on 2026-04-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0016_ventepharmacie_patient_alter_lignevente_type_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prescrite', models.PositiveIntegerField(verbose_name='Quantité Prescrite')),
                ('quantite_payee', models.PositiveIntegerField(default=0, verbose_name='Quantité Payée')),
                ('quantite_delivree', models.PositiveIntegerField(default=0, verbose_name='Quantité Délivrée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_prescrites', to='hopital_site.medicament')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='hopital_site.ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'Ordonnance",
                'verbose_name_plural': "Lignes d'Ordonnance",
            },
        ),
    ]
