# Generated by Django 6.0.3 on 2026-04-09 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0017_ligneordonnance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ligneordonnance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logpharmacie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='signesvitaux',
            options={'ordering': ['-date_prelevement']},
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='numero',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix_journalier',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='resultat_labo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ligneordonnance',
            name='quantite_delivree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ligneordonnance',
            name='quantite_payee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ligneordonnance',
            name='quantite_prescrite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lit',
            name='est_occupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lit',
            name='nom_lit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='logpharmacie',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='contenu_prescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='est_delivré',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='instructions_posologie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='frequence_cardiaque',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='frequence_respiratoire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='infirmier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='poids',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='saturation_oxygene',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='signesvitaux',
            name='tension_arterielle',
            field=models.CharField(max_length=20),
        ),
    ]
