# Generated by Django 6.0.3 on 2026-04-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0018_alter_ligneordonnance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('LAPTOP', 'Ordinateur Portable'), ('DESKTOP', 'Ordinateur de Bureau'), ('TABLET', 'Tablette'), ('PRINTER', 'Imprimante'), ('MEDICAL', 'Appareil Médical'), ('TECH', 'Matériel Technique (Groupe, etc.)')], max_length=50)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('etat_actuel', models.CharField(choices=[('FONCTIONNEL', 'En marche'), ('PANNE', 'En Panne'), ('REPARATION', 'En Réparation'), ('DECLASSE', 'Hors service / Déclassé')], default='FONCTIONNEL', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Caractéristique technique (RAM, Stockage, etc.)', null=True)),
                ('service_affecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='hopital_site.service')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('description_panne', models.TextField(help_text='Expliquez le problème constaté')),
                ('est_repare', models.BooleanField(default=False)),
                ('date_reparation', models.DateTimeField(blank=True, null=True)),
                ('rapport_technique', models.TextField(blank=True, help_text='Ce qui a été fait pour réparer', null=True)),
                ('cout_reparation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_pannes', to='hopital_site.materiel')),
            ],
        ),
    ]
