# Generated by Django 6.0.3 on 2026-04-16 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0019_materiel_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Matricule')),
                ('date_embauche', models.DateField(verbose_name='Date de début / Embauche')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée (CDI)'), ('CDD', 'Contrat à Durée Déterminée (CDD)'), ('STAGE_PRO', 'Stagiaire Professionnel'), ('STAGE_ACA', 'Stagiaire Académique (Non payé)'), ('PRESTAIRE', 'Consultant / Prestataire Extérieur')], default='CDI', max_length=20)),
                ('salaire_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salaire de base')),
                ('carte_identite', models.FileField(blank=True, null=True, upload_to='rh/identite/', verbose_name="Carte d'identité")),
                ('diplome', models.FileField(blank=True, null=True, upload_to='rh/diplomes/', verbose_name='Diplôme')),
                ('contrat_signe', models.FileField(blank=True, null=True, upload_to='rh/contrats/', verbose_name='Contrat signé')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-date_embauche'],
            },
        ),
    ]
