# Generated by Django 6.0.3 on 2026-04-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0020_employe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('CASH', 'Espèces (Cash)'), ('MPESA', 'M-Pesa')], default='CASH', max_length=10, verbose_name='Mode de paiement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction / Référence'),
        ),
    ]
