# Generated by Django 6.0.3 on 2026-04-19 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0021_alter_paiement_options_paiement_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventepharmacie',
            name='ordonnance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='hopital_site.ordonnance'),
        ),
    ]
