# Generated by Django 6.0.3 on 2026-04-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0022_ventepharmacie_ordonnance'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='ordonnance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='hopital_site.ordonnance'),
        ),
    ]
