# Generated by Django 6.0.3 on 2026-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0023_facture_ordonnance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif (Fiche, etc.)'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins / Nursing'), ('PHARMA', 'Pharmacie')], max_length=10),
        ),
    ]
