# Generated by Django 6.0.3 on 2026-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0024_alter_prestation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneordonnance',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facture',
            name='prix_fixe_cdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='facture',
            name='taux_fixe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
