# Generated by Django 6.0.3 on 2026-04-21 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0025_ligneordonnance_paye_alter_facture_prix_fixe_cdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client_externe', models.CharField(blank=True, help_text='Pour les clients sans dossier', max_length=200, null=True)),
                ('total_a_payer_cdf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_fixe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('ordonnance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facture_pharma', to='hopital_site.ordonnance')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures_pharma', to='hopital_site.patient')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacturePharma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire_applique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='hopital_site.facturepharmacie')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.medicament')),
            ],
        ),
    ]
