# Generated by Django 6.0.3 on 2026-04-21 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0026_facturepharmacie_lignefacturepharma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={},
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture_pharma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='hopital_site.facturepharmacie'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='hopital_site.facture'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('CASH', 'Espèces (Cash)'), ('MPESA', 'M-Pesa')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
