# Generated by Django 6.0.3 on 2026-04-22 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0027_alter_paiement_options_paiement_facture_pharma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={},
        ),
        migrations.RemoveField(
            model_name='employe',
            name='carte_identite',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='contrat_signe',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='diplome',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='groupe_sanguin',
        ),
        migrations.RemoveField(
            model_name='lignevente',
            name='type_vente',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='cout_reparation',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='date_signalement',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='rapport_technique',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materiel',
            name='modele',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.CharField(choices=[('VIP', 'VIP'), ('STANDARD', 'Standard'), ('COMMUNE', 'Salle Commune')], default='STANDARD', max_length=50),
        ),
        migrations.AlterField(
            model_name='configurationhopital',
            name='taux_usd_en_cdf',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='type_contrat',
            field=models.CharField(default='CDI', max_length=20),
        ),
        migrations.AlterField(
            model_name='examenprescrit',
            name='laborantin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturepharmacie',
            name='nom_client_externe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description_panne',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat_actuel',
            field=models.CharField(default='FONCTIONNEL', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='service_affecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.service'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('PHARMA', 'Pharmacie')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ventepharmacie',
            name='statut',
            field=models.CharField(default='VALIDE', max_length=10),
        ),
    ]
