# Generated by Django 6.0.3 on 2026-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0028_alter_employe_options_remove_employe_carte_identite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventepharmacie',
            name='est_paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventepharmacie',
            name='nom_client_externe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
