# Generated by Django 6.0.3 on 2026-04-30 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0029_ventepharmacie_est_paye_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacturepharma',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture_set', to='hopital_site.facturepharmacie'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente_set', to='hopital_site.facturepharmacie'),
        ),
        migrations.CreateModel(
            name='FactureClientPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(default='Client de passage', max_length=200)),
                ('total_a_payer_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_fixe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture_comptoir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='hopital_site.factureclientpharmacie'),
        ),
        migrations.CreateModel(
            name='LigneVenteSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='hopital_site.factureclientpharmacie')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hopital_site.medicament')),
            ],
        ),
    ]
