# Generated by Django 6.0.3 on 2026-05-02 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0030_alter_lignefacturepharma_facture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneventesimple',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='hopital_site.factureclientpharmacie'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='service_affecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='hopital_site.service'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('PHARMA', 'Pharmacie'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie')], max_length=10),
        ),
    ]
