# Generated by Django 6.0.3 on 2026-05-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0031_alter_ligneventesimple_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupationlit',
            name='motif_admission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='occupationlit',
            name='termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occupationlit',
            name='lit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='hopital_site.lit'),
        ),
        migrations.AlterField(
            model_name='occupationlit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='hopital_site.patient'),
        ),
    ]
