# Generated by Django 6.0.3 on 2026-05-05 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital_site', '0032_occupationlit_motif_admission_occupationlit_termine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoinHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_soin', models.CharField(max_length=200)),
                ('cout_soin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_soin', models.DateTimeField(default=django.utils.timezone.now)),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='hopital_site.occupationlit')),
            ],
        ),
    ]
