# Generated by Django 6.0.5 on 2026-06-02 18:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Sans nom', max_length=50)),
                ('est_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_usd_en_cdf', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du Taux',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('contact_responsable', models.CharField(max_length=100, verbose_name='Numéro du responsable')),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement")),
            ],
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('MED', 'Acte Médical'), ('CHIR', 'Acte Chirurgical'), ('CONS_MAT', 'Consultation Maternité'), ('MAT', 'Forfait Maternité / Accouchement')], max_length=10, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix (USD)')),
                ('valeur_normale', models.CharField(blank=True, help_text='Ex: 70-110 mg/dl, Négatif, etc.', max_length=150, null=True, verbose_name='Valeur Normale / Référence (Labo uniquement)')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix_nuitée', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_consultation', models.TextField(verbose_name='Motif')),
                ('histoire_maladie', models.TextField(verbose_name='Histoire de la maladie')),
                ('examen_physique', models.TextField(verbose_name='Examen physique')),
                ('complement_d_anamnese', models.CharField(max_length=200, null=True)),
                ('hypothese_diagnostique', models.TextField(verbose_name='Hypothèse diagnostique')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('consultation_payee', models.BooleanField(default=False, verbose_name='Consultation payée')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('LABO_REACTIF', 'Réactifs & Matériel Labo'), ('PHARMA_STOCK', 'Achat Stock Pharmacie'), ('CARBURANT', 'Carburant Générateur'), ('MAINTENANCE', 'Maintenance & Réparations'), ('ADMIN', 'Frais Administratifs & Bureau'), ('SALAIRE', 'Avances & Salaires Personnel'), ('AUTRE', 'Autre dépense')], max_length=50, verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiaire', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bénéficiaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lit', models.CharField(max_length=50)),
                ('est_occupe', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='apps.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='Maternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('terme_prevu', models.DateField()),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('est_paye', models.BooleanField(default=False, verbose_name="Frais d'ouverture réglés")),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescrite', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_ordonnance', models.CharField(choices=[('URGENCE', 'Ordonnance d’Urgence'), ('DEFINITIVE', 'Ordonnance Définitive')], default='URGENCE', max_length=20)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('observation', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('posologie', models.CharField(max_length=255)),
                ('duree', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('STOPPE', 'Stoppé')], default='EN_COURS', max_length=20)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='apps.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='LigneMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(help_text='ex: 1 tab 3 fois par jour', max_length=200)),
                ('duree', models.CharField(help_text='ex: 5 jours', max_length=100)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('STOPPE', 'Stoppé / Changé')], default='EN_COURS', max_length=20)),
                ('motif_arret', models.TextField(blank=True, help_text='Pourquoi le médecin a changé ce médicament', null=True)),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_medicaments', to='apps.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès')], max_length=20)),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Dette / Reste à payer')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.consultation')),
                ('dossier_maternite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.maternite')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture_liee', to='apps.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(editable=False, max_length=20, unique=True)),
                ('noms', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('fiche_payee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='apps.service')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient'),
        ),
        migrations.AddField(
            model_name='maternite',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_maternite', to='apps.patient'),
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_admission', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations', to='apps.lit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sejours', to='apps.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
            },
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.TextField(blank=True, help_text='Note du médecin pour le technicien')),
                ('resultat', models.TextField(blank=True, null=True)),
                ('image_resultat', models.ImageField(blank=True, null=True, upload_to='resultats_examens/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='apps.consultation')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_realises', to=settings.AUTH_USER_MODEL)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMaternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('tension_arterielle', models.CharField(max_length=10, verbose_name='Tension artérielle')),
                ('hauteur_uterine', models.IntegerField(verbose_name='Hauteur utérine (cm)')),
                ('bruits_cardiaques_foetaux', models.CharField(max_length=20, verbose_name='BCF')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes médicales')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dossier_maternite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='apps.maternite')),
                ('prestation', models.ForeignKey(limit_choices_to={'categorie': 'CONS_MAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisation', models.CharField(default='oui', max_length=30)),
                ('userKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fonction', to=settings.AUTH_USER_MODEL)),
                ('fonctionKey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.role')),
            ],
        ),
        migrations.CreateModel(
            name='SigneVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tension_arterielle', models.CharField(max_length=10)),
                ('frequence_cardiaque', models.IntegerField()),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True)),
                ('saturation_oxygene', models.IntegerField(blank=True, null=True)),
                ('date_prelevement', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_consulte', models.BooleanField(default=False)),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='triage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.signevital'),
        ),
        migrations.CreateModel(
            name='SuiviQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True)),
                ('etat_general', models.TextField(verbose_name='État général du patient')),
                ('constantes_du_jour', models.TextField(verbose_name='Constantes (TA, Pouls, Temp...)')),
                ('soins_effectues', models.TextField(verbose_name='Soins et médicaments administrés')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_journaliers', to='apps.hospitalisation')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi Quotidien',
                'verbose_name_plural': 'Suivis Quotidiens',
                'ordering': ['-date_suivi'],
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='type_chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.typechambre'),
        ),
    ]
