# Generated by Django 6.0.6 on 2026-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpharmacie',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
