# Generated by Django 6.0.5 on 2026-06-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient_externe', models.CharField(blank=True, max_length=255, null=True)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('adresse_avenue', models.CharField(max_length=100, verbose_name='Avenue')),
                ('adresse_numero', models.CharField(max_length=20, verbose_name='Numéro')),
                ('adresse_quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('adresse_commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('date_deces', models.DateTimeField(verbose_name='Date et heure du décès')),
                ('cause_deces', models.TextField(verbose_name='Cause du décès')),
                ('etablissement', models.CharField(default='Hôpital Paradis Center', max_length=255)),
                ('certifie_par', models.CharField(max_length=255, verbose_name='Nom du médecin')),
                ('numero_cnom', models.CharField(max_length=50, verbose_name='Numéro CNOM du médecin')),
                ('notes', models.TextField(blank=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.patient')),
            ],
            options={
                'verbose_name': 'Certificat de décès',
                'verbose_name_plural': 'Certificats de décès',
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='deces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.deces'),
        ),
    ]
