# Generated by Django 6.0.6 on 2026-06-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_produitpharmacie_stock_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('PHARMACIE', 'Pharmacie'), ('EXAMEN_EXTERNE', 'Examen Externe')], max_length=20),
        ),
        migrations.CreateModel(
            name='DemandeExamenExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=15)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='apps.clientexterne')),
                ('prestations', models.ManyToManyField(to='apps.prestation', verbose_name='Examens choisis')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='demande_examen_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.demandeexamenexterne'),
        ),
    ]
