# Generated by Django 6.0.5 on 2026-06-02 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_deces_paiement_deces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.patient'),
        ),
    ]
