# Generated by Django 6.0.4 on 2026-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_role_fonction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('ADM', 'Administratif'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie')], max_length=10, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix (USD)')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
    ]
