# Generated by Django 6.0.5 on 2026-06-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_paiement_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='a_carte_fidelite',
            field=models.BooleanField(default=False, verbose_name='Possède carte de fidélité'),
        ),
        migrations.AddField(
            model_name='patient',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.entreprise', verbose_name='Entreprise (si conventionné)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='type_patient',
            field=models.CharField(choices=[('SIMPLE', 'Patient Simple'), ('FIDELE', 'Patient Fidèle'), ('CONVENTIONNE', 'Patient Conventionné')], default='SIMPLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité')], max_length=20),
        ),
    ]
