# Generated by Django 6.0.6 on 2026-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_clientexterne_alter_paiement_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexterne',
            name='poids',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clientexterne',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=20, null=True),
        ),
    ]
