# Generated by Django 6.0.5 on 2026-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_patient_a_carte_fidelite_patient_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_reduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
