# Generated by Django 6.0.6 on 2026-06-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_clientexterne_poids_clientexterne_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientexterne',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
