# Generated by Django 6.0.6 on 2026-06-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_clientexterne_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenExterneResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé')], default='EN_ATTENTE', max_length=20)),
                ('rapport', models.TextField(verbose_name="Résultat / Rapport d'examen")),
                ('date_resultat', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_examens', to='apps.demandeexamenexterne')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.prestation')),
            ],
            options={
                'verbose_name': "Résultat d'examen externe",
                'verbose_name_plural': 'Résultats des examens externes',
            },
        ),
    ]
