# Generated by Django 6.0.4 on 2026-05-10 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_paiement_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigneVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tension_arterielle', models.CharField(max_length=10)),
                ('frequence_cardiaque', models.IntegerField()),
                ('frequence_respiratoire', models.IntegerField(blank=True, null=True)),
                ('saturation_oxygene', models.IntegerField(blank=True, null=True)),
                ('date_prelevement', models.DateTimeField(auto_now_add=True)),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient')),
            ],
        ),
    ]
