# Generated by Django 6.0.5 on 2026-06-07 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_paiement_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('HOSPITALISATION', 'Hospitalisation'), ('SALLE_SOINS', 'Salle de Soins'), ('BLOC_OPERATOIRE', 'Bloc Opératoire'), ('SORTIE', 'Sortie/Retour à domicile')], max_length=50)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_orientation', models.DateTimeField(auto_now_add=True)),
                ('est_admis', models.BooleanField(default=False)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orientation', to='apps.consultation')),
                ('medecin_orientateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientations_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoinOccasionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=200)),
                ('date_soin', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.prestation')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='soin_occasionnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='apps.soinoccasionnel'),
        ),
    ]
