# Generated by Django 6.0.4 on 2026-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_signevital'),
    ]

    operations = [
        migrations.AddField(
            model_name='signevital',
            name='est_consulte',
            field=models.BooleanField(default=False),
        ),
    ]
