# Generated by Django 6.0.6 on 2026-06-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_examenexterneresultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='apps.entreprise'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('PHARMACIE', 'Pharmacie'), ('EXAMEN_EXTERNE', 'Examen Externe'), ('ENTREPRISE', 'Paiement Entreprise')], max_length=20),
        ),
    ]
