# Generated by Django 6.0.5 on 2026-06-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_orientation_soinoccasionnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='soin_occasionnel',
        ),
        migrations.AddField(
            model_name='soinoccasionnel',
            name='paiement',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='soins_lies', to='apps.paiement'),
            preserve_default=False,
        ),
    ]
