# Generated by Django 6.0.6 on 2026-06-17 08:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_paiement_entreprise_alter_paiement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='dette_mensuelle',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Dette mensuelle'),
        ),
    ]
