# Generated by Django 6.0.4 on 2026-05-12 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_signevital_est_consulte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_consultation', models.TextField(verbose_name='Motif')),
                ('histoire_maladie', models.TextField(verbose_name='Histoire de la maladie')),
                ('examen_physique', models.TextField(verbose_name='Examen physique')),
                ('hypothese_diagnostique', models.TextField(verbose_name='Hypothèse diagnostique')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('triage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.signevital')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.TextField(blank=True, help_text='Note du médecin pour le technicien')),
                ('resultat', models.TextField(blank=True, null=True)),
                ('image_resultat', models.ImageField(blank=True, null=True, upload_to='resultats_examens/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='apps.consultation')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.prestation')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_realises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescrite', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True, help_text="Note générale sur l'ordonnance")),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='LigneMedicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(help_text='ex: 1 tab 3 fois par jour', max_length=200)),
                ('duree', models.CharField(help_text='ex: 5 jours', max_length=100)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('STOPPE', 'Stoppé / Changé')], default='EN_COURS', max_length=20)),
                ('motif_arret', models.TextField(blank=True, help_text='Pourquoi le médecin a changé ce médicament', null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='apps.ordonnance')),
            ],
        ),
    ]
