# Generated by Django 6.0.5 on 2026-06-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_remove_paiement_soin_occasionnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soinoccasionnel',
            name='est_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
