# Generated by Django 6.0.6 on 2026-06-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_entreprise_dette_mensuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('SCAN', 'Scanner'), ('IRM', 'IRM'), ('CARDIO', 'Cardiographie'), ('GYNECO', 'Gynécographie'), ('ONCO', 'Oncologie'), ('ORTHO', 'Orthopédie'), ('DERMA', 'Dermatologie'), ('OPHTA', 'Ophtalmologie'), ('PSY', 'Psychiatrie'), ('KINE', 'Rééducation / Kinésithérapie'), ('MED', 'Acte Médical'), ('CHIR', 'Acte Chirurgical'), ('CONS_MAT', 'Consultation Maternité'), ('MAT', 'Forfait Maternité / Accouchement')], max_length=10, verbose_name='Catégorie'),
        ),
    ]
