# Generated by Django 6.0.4 on 2026-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_consultation_demandeexamen_ordonnance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamen',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='type_ordonnance',
            field=models.CharField(choices=[('URGENCE', 'Ordonnance d’Urgence'), ('DEFINITIVE', 'Ordonnance Définitive')], default='URGENCE', max_length=20),
        ),
    ]
