# Generated by Django 6.0.4 on 2026-05-14 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_demandeexamen_quantite_ordonnance_type_ordonnance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
