# Generated by Django 6.0.5 on 2026-06-08 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_soinoccasionnel_est_effectue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom commercial / DCI')),
                ('forme', models.CharField(help_text='Ex: Comprimé, Sirop, Ampoule, Pommade', max_length=100)),
                ('dosage', models.CharField(help_text='Ex: 500mg, 250mg/5ml', max_length=50)),
                ('categorie', models.CharField(max_length=100, verbose_name='Catégorie (ex: Antibiotique)')),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente unitaire')),
                ('stock_total', models.PositiveIntegerField(default=0, verbose_name='Stock total actuel')),
            ],
            options={
                'verbose_name': 'Produit Pharmaceutique',
                'unique_together': {('nom', 'forme', 'dosage')},
            },
        ),
        migrations.CreateModel(
            name='LotPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_peremption', models.DateField()),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='apps.produitpharmacie')),
            ],
        ),
    ]
