# Generated by Django 6.0.6 on 2026-06-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_prestation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='compte_rendu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='apps.compterenduaccouchement'),
        ),
    ]
