# Generated by Django 6.0.5 on 2026-06-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_produitpharmacie_lotpharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitpharmacie',
            name='stock_total',
        ),
        migrations.AlterField(
            model_name='lotpharmacie',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_lots', to='apps.produitpharmacie'),
        ),
    ]
