# Generated by Django 6.0.6 on 2026-06-20 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_paiement_compte_rendu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheAccouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_accouchement', models.CharField(choices=[('NATUREL', 'Accouchement Naturel'), ('CESARIENNE', 'Césarienne')], max_length=20, verbose_name="Type d'accouchement")),
                ('sexe_bebe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe du bébé')),
                ('poids_bebe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids du bébé (kg)')),
                ('score_apgar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score Apgar')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Complications')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la fiche')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_accouchement', to='apps.consultation')),
                ('prestation', models.ForeignKey(limit_choices_to={'categorie': 'MAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.prestation', verbose_name='Forfait Maternité')),
            ],
        ),
    ]
