# Generated by Django 6.0.4 on 2026-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_service_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fiche_payee',
            field=models.BooleanField(default=False),
        ),
    ]
