# Generated by Django 6.0.5 on 2026-06-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_remove_produitpharmacie_stock_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortiePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vendue', models.PositiveIntegerField()),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sortie_stock', to='apps.paiement')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_sorties', to='apps.produitpharmacie')),
            ],
        ),
    ]
