# Generated by Django 6.0.6 on 2026-06-20 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_ficheaccouchement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdonnanceExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('note_globale', models.TextField(blank=True, help_text='Instructions générales', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances_externes', to='apps.clientexterne')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordonnance Client Externe',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='OrdonnanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Médicament ou Examen')),
                ('posologie', models.TextField(verbose_name='Posologie / Instructions')),
                ('quantite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quantité')),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.ordonnanceexterne')),
            ],
        ),
    ]
