# Generated by Django 6.0.4 on 2026-05-15 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_patient_fiche_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demandeexamen',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lignemedicament',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date_prescrite',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='signevital',
            name='date_prelevement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
