# Generated by Django 6.0.4 on 2026-05-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_consultation_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='complement_d_anamnese',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
