# Generated by Django 6.0.5 on 2026-06-08 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_sortiepharmacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortiepharmacie',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='les_sorties', to='apps.paiement'),
        ),
    ]
