# Generated by Django 6.0.6 on 2026-06-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_ordonnanceexterne_ordonnanceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='antecedent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
