# Generated by Django 6.0.6 on 2026-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_consultation_antecedent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suiviquotidien',
            name='pouls',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Pouls'),
        ),
        migrations.AddField(
            model_name='suiviquotidien',
            name='ta',
            field=models.CharField(default='N/A', max_length=20, verbose_name='TA'),
        ),
        migrations.AddField(
            model_name='suiviquotidien',
            name='temp',
            field=models.CharField(default='N/A', max_length=20, verbose_name='Temp (°C)'),
        ),
    ]
