# Generated by Django 6.0.5 on 2026-06-10 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_sortiepharmacie_paiement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constantes_pre_op', models.TextField(verbose_name='Constantes pré-opératoires')),
                ('date_programmee', models.DateTimeField(default=django.utils.timezone.now)),
                ('acte_realise', models.TextField(blank=True, null=True, verbose_name='Compte-rendu opératoire')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('chirurgien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chirurgies_realisees', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloc_op', to='apps.consultation')),
            ],
        ),
    ]
