# Generated by Django 6.0.4 on 2026-05-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_consultation_complement_d_anamnese'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.consultation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie')], max_length=20),
        ),
    ]
