# Generated by Django 6.0.6 on 2026-06-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_suiviquotidien_pouls_suiviquotidien_ta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=100)),
                ('voie_administration', models.CharField(max_length=50)),
                ('matin', models.BooleanField(default=False)),
                ('midi', models.BooleanField(default=False)),
                ('soir', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_items', to='apps.hospitalisation')),
            ],
        ),
    ]
