# Generated by Django 6.0.5 on 2026-06-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_blocoperatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocoperatoire',
            name='prestation',
            field=models.ForeignKey(limit_choices_to={'categorie': 'CHIR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.prestation', verbose_name="Type d'intervention"),
        ),
    ]
