# Generated by Django 6.0.4 on 2026-05-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_paiement_consultation_alter_paiement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Dette / Reste à payer'),
        ),
    ]
