# Generated by Django 6.0.5 on 2026-06-10 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_blocoperatoire_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='bloc_op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.blocoperatoire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('CHIRURGIE', 'Actes de Chirurgie')], max_length=20),
        ),
    ]
