# Generated by Django 6.0.6 on 2026-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_kardex'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='date_debut',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
