# Generated by Django 6.0.4 on 2026-05-19 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_paiement_reste_a_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(choices=[('LABO_REACTIF', 'Réactifs & Matériel Labo'), ('PHARMA_STOCK', 'Achat Stock Pharmacie'), ('CARBURANT', 'Carburant Générateur'), ('MAINTENANCE', 'Maintenance & Réparations'), ('ADMIN', 'Frais Administratifs & Bureau'), ('SALAIRE', 'Avances & Salaires Personnel'), ('AUTRE', 'Autre dépense')], max_length=50, verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3)),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now)),
                ('beneficiaire', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bénéficiaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
            },
        ),
    ]
