# Generated by Django 6.0.5 on 2026-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='valeur_normale',
            field=models.CharField(blank=True, help_text='Ex: 70-110 mg/dl, Négatif, etc. Utilisé uniquement pour le Laboratoire.', max_length=150, null=True, verbose_name='Valeur Normale / Référence (Labo uniquement)'),
        ),
    ]
