# Generated by Django 6.0.5 on 2026-06-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_paiement_bloc_op_alter_paiement_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité')], max_length=20),
        ),
    ]
