# Generated by Django 6.0.6 on 2026-06-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_kardex_date_debut'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
    ]
