# Generated by Django 6.0.5 on 2026-06-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_alter_paiement_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orientation',
            name='destination',
            field=models.CharField(choices=[('PHARMACIE', 'Pharmacie'), ('HOSPITALISATION', 'Hospitalisation'), ('SALLE_SOINS', 'Salle de Soins'), ('BLOC_OPERATOIRE', 'Bloc Opératoire'), ('ACCOUCHEMENT', 'Accouchement'), ('SORTIE', 'Sortie/Retour à domicile')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('PHARMACIE', 'Pharmacie')], max_length=20),
        ),
    ]
