# Generated by Django 6.0.5 on 2026-06-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_orientation_destination_alter_paiement_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRenduAccouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_accouchement', models.CharField(choices=[('NATUREL', 'Accouchement Simple (Voie basse)'), ('CESARIENNE', 'Accouchement par Césarienne')], max_length=20)),
                ('details_acte', models.TextField(verbose_name="Détails de l'intervention / Rapport")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cr_accouchement', to='apps.consultation')),
                ('prestation', models.ForeignKey(limit_choices_to={'categorie': 'MAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.prestation', verbose_name='Forfait / Prestation Maternité')),
            ],
        ),
    ]
