# Generated by Django 6.0.5 on 2026-05-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_alter_fonction_userkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Type de chambre')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de Chambre',
                'verbose_name_plural': 'Types de Chambres',
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ou_numero', models.CharField(max_length=50, unique=True, verbose_name='Nom / Numéro de la chambre')),
                ('prix_par_jour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par jour (Nuitée)')),
                ('localisation', models.CharField(blank=True, help_text='Ex: Pavillon A, 2ème étage', max_length=150, null=True)),
                ('est_active', models.BooleanField(default=True, help_text='Décocher si la chambre est en travaux ou indisponible', verbose_name='En service')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='apps.typechambre', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ou_code', models.CharField(max_length=50, verbose_name='Code / Numéro du lit')),
                ('est_occupe', models.BooleanField(default=False, verbose_name='Occupé')),
                ('est_actif', models.BooleanField(default=True, help_text='Décocher si le lit est cassé/en maintenance', verbose_name='Opérationnel')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='apps.chambre', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Lit',
                'verbose_name_plural': 'Lits',
                'unique_together': {('chambre', 'nom_ou_code')},
            },
        ),
    ]
