# Generated by Django 6.0.6 on 2026-06-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdonnanceSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prescriptions', models.TextField(verbose_name='Médicaments prescrits')),
                ('recommandations', models.TextField(verbose_name='Conseils et hygiène de vie')),
                ('date_prochain_rdv', models.DateField(blank=True, null=True, verbose_name='Date de suivi')),
                ('medecin_nom', models.CharField(blank=True, max_length=255)),
                ('hospitalisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance_sortie', to='apps.hospitalisation')),
            ],
            options={
                'verbose_name': 'Ordonnance de Sortie',
                'verbose_name_plural': 'Ordonnances de Sortie',
            },
        ),
    ]
