# Generated by Django 6.0.6 on 2026-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_compterenduaccouchement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpharmacie',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock total actuel'),
        ),
    ]
