# Generated by Django 6.0.5 on 2026-05-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_typechambre_chambre_lit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chambre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typechambre',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='nom_ou_numero',
        ),
        migrations.RemoveField(
            model_name='chambre',
            name='prix_par_jour',
        ),
        migrations.RemoveField(
            model_name='typechambre',
            name='description',
        ),
        migrations.AddField(
            model_name='chambre',
            name='nom',
            field=models.CharField(default='Sans nom', max_length=50),
        ),
        migrations.AddField(
            model_name='lit',
            name='nom_lit',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typechambre',
            name='prix_nuitée',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='est_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.typechambre'),
        ),
        migrations.AlterField(
            model_name='lit',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='apps.chambre'),
        ),
        migrations.AlterField(
            model_name='lit',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lit',
            name='est_occupe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typechambre',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='lit',
            name='nom_ou_code',
        ),
    ]
