# Generated by Django 6.0.5 on 2026-05-27 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_chambre_options_alter_lit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_admission', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_COURS', max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupations', to='apps.lit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sejours', to='apps.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
            },
        ),
    ]
