# Generated by Django 6.0.6 on 2026-06-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_produitpharmacie_stock_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='apps.entreprise', verbose_name='Entreprise (si conventionné)'),
        ),
    ]
