# Generated by Django 6.0.6 on 2026-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_paiement_hospitalisation_alter_paiement_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='est_payee',
            field=models.BooleanField(default=False),
        ),
    ]
