# Generated by Django 6.0.6 on 2026-06-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_hospitalisation_est_payee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kardex',
            old_name='date_debut',
            new_name='date_prescription',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='matin',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='midi',
        ),
        migrations.RemoveField(
            model_name='kardex',
            name='soir',
        ),
        migrations.AlterField(
            model_name='kardex',
            name='est_actif',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='medicament',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='posologie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='voie_administration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AdministrationKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admin', models.DateField()),
                ('matin', models.BooleanField(default=False)),
                ('midi', models.BooleanField(default=False)),
                ('soir', models.BooleanField(default=False)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='apps.kardex')),
            ],
            options={
                'unique_together': {('kardex', 'date_admin')},
            },
        ),
    ]
