# Generated by Django 6.0.5 on 2026-05-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_hospitalisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='consultation_payee',
            field=models.BooleanField(default=False, verbose_name='Consultation payée'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie')], max_length=10, verbose_name='Catégorie'),
        ),
    ]
