# Generated by Django 6.0.6 on 2026-06-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_patient_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSoins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_facture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.prestation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps.sessionsoins')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.sessionsoins'),
        ),
    ]
