# Generated by Django 6.0.6 on 2026-06-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_rename_date_debut_kardex_date_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(choices=[('bon', 'En bon état'), ('panne', 'En panne'), ('maintenance', 'En maintenance'), ('reforme', 'À réformer')], default='bon', max_length=20)),
                ('date_acquisition', models.DateField()),
                ('date_derniere_maintenance', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.categorieequipement')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.service')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='InterventionMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_panne', models.TextField()),
                ('date_panne', models.DateTimeField(auto_now_add=True)),
                ('date_reparation', models.DateTimeField(blank=True, null=True)),
                ('repare', models.BooleanField(default=False)),
                ('technicien', models.CharField(blank=True, max_length=100)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='apps.equipement')),
            ],
        ),
    ]
