# Generated by Django 6.0.6 on 2026-06-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_sessionsoins_lignefacture_consultation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.sessionsoins'),
        ),
    ]
