# Generated by Django 6.0.5 on 2026-05-28 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_consultation_consultation_payee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lignemedicament',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_medicaments', to='apps.ordonnance'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('posologie', models.CharField(max_length=255)),
                ('duree', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('STOPPE', 'Stoppé')], default='EN_COURS', max_length=20)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='apps.ordonnance')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviQuotidien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True)),
                ('etat_general', models.TextField(verbose_name='État général du patient')),
                ('constantes_du_jour', models.TextField(verbose_name='Constantes (TA, Pouls, Temp...)')),
                ('soins_effectues', models.TextField(verbose_name='Soins et médicaments administrés')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_journaliers', to='apps.hospitalisation')),
                ('infirmier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi Quotidien',
                'verbose_name_plural': 'Suivis Quotidiens',
                'ordering': ['-date_suivi'],
            },
        ),
    ]
