# Generated by Django 6.0.6 on 2026-06-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_paiement_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='signevital',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signes_vitaux', to='apps.sessionsoins'),
        ),
    ]
