# Generated by Django 6.0.5 on 2026-05-31 16:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('MED', 'Acte Médical (Hospitalisation)'), ('CHIR', 'Acte Chirurgical (Hospitalisation)')], max_length=10, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='valeur_normale',
            field=models.CharField(blank=True, help_text='Ex: 70-110 mg/dl, Négatif, etc.', max_length=150, null=True, verbose_name='Valeur Normale / Référence (Labo uniquement)'),
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix Facturé')),
                ('remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Remise/Réduction')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='apps.facture')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.prestation')),
            ],
        ),
    ]
