# Generated by Django 6.0.5 on 2026-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_prestation_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('MED', 'Acte Médical'), ('CHIR', 'Acte Chirurgical')], max_length=10, verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='LigneFacture',
        ),
    ]
