# Generated by Django 6.0.5 on 2026-06-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_prestation_categorie_delete_lignefacture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admission', models.DateTimeField(auto_now_add=True)),
                ('terme_prevu', models.DateField()),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_maternite', to='apps.patient')),
            ],
        ),
    ]
