# Generated by Django 6.0.5 on 2026-06-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_maternite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maternite',
            name='groupe_sanguin',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
    ]
