# Generated by Django 6.0.5 on 2026-06-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_alter_maternite_groupe_sanguin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('MED', 'Acte Médical'), ('CHIR', 'Acte Chirurgical'), ('MAT', 'Maternité')], max_length=10, verbose_name='Catégorie'),
        ),
    ]
