# Generated by Django 6.0.5 on 2026-06-02 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_alter_prestation_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMaternite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (kg)')),
                ('tension_arterielle', models.CharField(max_length=10, verbose_name='Tension artérielle')),
                ('hauteur_uterine', models.IntegerField(verbose_name='Hauteur utérine (cm)')),
                ('bruits_cardiaques_foetaux', models.CharField(max_length=20, verbose_name='BCF')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes médicales')),
                ('dossier_maternite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='apps.maternite')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
