# Generated by Django 6.0.5 on 2026-06-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_consultationmaternite'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationmaternite',
            name='prestation',
            field=models.ForeignKey(limit_choices_to={'categorie': 'CONS_MAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.prestation'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(choices=[('ADM', 'Administratif'), ('CONS', 'Consultation'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie'), ('MED', 'Acte Médical'), ('CHIR', 'Acte Chirurgical'), ('CONS_MAT', 'Consultation Maternité'), ('MAT', 'Forfait Maternité / Accouchement')], max_length=10, verbose_name='Catégorie'),
        ),
    ]
