# Generated by Django 6.0.5 on 2026-06-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_consultationmaternite_prestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maternite',
            name='est_paye',
            field=models.BooleanField(default=False, verbose_name="Frais d'ouverture réglés"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='dossier_maternite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='apps.maternite'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité')], max_length=20),
        ),
    ]
