# Generated by Django 6.0.5 on 2026-06-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_maternite_est_paye_paiement_dossier_maternite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient_externe', models.CharField(blank=True, max_length=255, null=True)),
                ('date_deces', models.DateTimeField()),
                ('cause_deces', models.TextField()),
                ('certifie_par', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.patient')),
            ],
        ),
    ]
